### ISSUE TITLE
[BUG] Cannot install the package using poetry 1.4.X

### ISSUE THREAD

**Issue by integrajerome** [yuval9313/FastApi-RESTful#175]
Error installing the package using poetry 1.4.0.

To reproduce: install or upgrade to poetry 4 and try to install latest fastapi-restful.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/91475647/222508224-531e2220-31c5-4c64-820b-a1d189eba979.png">

**Comment by Abashinos** [comment]
same here

**Comment by jgentil** [comment]
it looks like it's case sensitive.  The file inflates as `fastapi_restful-0.4.3.dist-info/WHEEL` but it's looking for `FastApi_RESTful-0.4.3.dist-info/WHEEL`

This is probably because the .whl filename on pypi is named `FastApi_RESTful-0.4.3-py3-none-any.whl` and Poetry is matching the exact case of the whl file to the expected dist-info.  

This is a regression in Poetry 1.4.0 and I've submitted a bug here:  https://github.com/python-poetry/poetry/issues/7635

However, as a workaround, you can download the .whl file from PyPI itself [here](https://files.pythonhosted.org/packages/3d/f8/f152c23d669efab0c78ccbc9cb0500c3c1c2a07ab492cf9fac2ac91ffd74/FastApi_RESTful-0.4.3-py3-none-any.whl), rename it to the proper lower-case name, and then use `poetry add` to install it.

```
wget https://files.pythonhosted.org/packages/3d/f8/f152c23d669efab0c78ccbc9cb0500c3c1c2a07ab492cf9fac2ac91ffd74/FastApi_RESTful-0.4.3-py3-none-any.whl
mv FastApi_RESTful-0.4.3-py3-none-any.whl fastapi_restful-0.4.3-py3-none-any.whl
poetry add ./fastapi_restful-0.4.3-py3-none-any.whl
```

@yuval9313 if you could change the case of the project in `pyproject.toml` and rename the source directory, that would fix this issue.

**Comment by Abashinos** [comment]
> it looks like it's case sensitive. The file inflates as `fastapi_restful-0.4.3.dist-info/WHEEL` but it's looking for `FastApi_RESTful-0.4.3.dist-info/WHEEL`
> 
> This is probably because the .whl filename on pypi is named `FastApi_RESTful-0.4.3-py3-none-any.whl` and Poetry is matching the exact case of the whl file to the expected dist-info.
> 
> This is a regression in Poetry 1.4.0 and I've submitted a bug here: [python-poetry/poetry#7572](https://github.com/python-poetry/poetry/issues/7572)
> 
> However, as a workaround, you can download the .whl file from PyPI itself [here](https://files.pythonhosted.org/packages/3d/f8/f152c23d669efab0c78ccbc9cb0500c3c1c2a07ab492cf9fac2ac91ffd74/FastApi_RESTful-0.4.3-py3-none-any.whl), rename it to the proper lower-case name, and then use `poetry add` to install it.
> 
> ```
> wget https://files.pythonhosted.org/packages/3d/f8/f152c23d669efab0c78ccbc9cb0500c3c1c2a07ab492cf9fac2ac91ffd74/FastApi_RESTful-0.4.3-py3-none-any.whl
> mv FastApi_RESTful-0.4.3-py3-none-any.whl fastapi_restful-0.4.3-py3-none-any.whl
> poetry add ./fastapi_restful-0.4.3-py3-none-any.whl
> ```
> 
> @yuval9313 if you could change the case of the project in `pyproject.toml` and rename the source directory, that would fix this issue.

Thank you for the breakdown! 
I've opted to downgrade poetry until they get to the fix, but, judging from the thread you linked, they won't be in much of a hurry.
Another [suggestion](https://github.com/python-poetry/poetry/issues/7572#issuecomment-1454036570) mentioned there is to exclusively disable the new installer with `poetry config installer.modern-installation false`, but remembering to enable it back once the issue is fixed would be a challenge in itself.

**Comment by yuval9313** [comment]
> it looks like it's case sensitive.  The file inflates as `fastapi_restful-0.4.3.dist-info/WHEEL` but it's looking for `FastApi_RESTful-0.4.3.dist-info/WHEEL`
> 
> This is probably because the .whl filename on pypi is named `FastApi_RESTful-0.4.3-py3-none-any.whl` and Poetry is matching the exact case of the whl file to the expected dist-info.  
> 
> This is a regression in Poetry 1.4.0 and I've submitted a bug here:  https://github.com/python-poetry/poetry/issues/7572
> 
> However, as a workaround, you can download the .whl file from PyPI itself [here](https://files.pythonhosted.org/packages/3d/f8/f152c23d669efab0c78ccbc9cb0500c3c1c2a07ab492cf9fac2ac91ffd74/FastApi_RESTful-0.4.3-py3-none-any.whl), rename it to the proper lower-case name, and then use `poetry add` to install it.
> 
> ```
> wget https://files.pythonhosted.org/packages/3d/f8/f152c23d669efab0c78ccbc9cb0500c3c1c2a07ab492cf9fac2ac91ffd74/FastApi_RESTful-0.4.3-py3-none-any.whl
> mv FastApi_RESTful-0.4.3-py3-none-any.whl fastapi_restful-0.4.3-py3-none-any.whl
> poetry add ./fastapi_restful-0.4.3-py3-none-any.whl
> ```
> 
> @yuval9313 if you could change the case of the project in `pyproject.toml` and rename the source directory, that would fix this issue.
> 

I assume you are right, I will do it but I must check with pypi to prevent 2 packages with the same name, one lower case and one like it is now

**Comment by integrajerome** [comment]
> it looks like it's case sensitive. The file inflates as `fastapi_restful-0.4.3.dist-info/WHEEL` but it's looking for `FastApi_RESTful-0.4.3.dist-info/WHEEL`
> 
> This is probably because the .whl filename on pypi is named `FastApi_RESTful-0.4.3-py3-none-any.whl` and Poetry is matching the exact case of the whl file to the expected dist-info.
> 
> This is a regression in Poetry 1.4.0 and I've submitted a bug here: [python-poetry/poetry#7572](https://github.com/python-poetry/poetry/issues/7572)
> 
> However, as a workaround, you can download the .whl file from PyPI itself [here](https://files.pythonhosted.org/packages/3d/f8/f152c23d669efab0c78ccbc9cb0500c3c1c2a07ab492cf9fac2ac91ffd74/FastApi_RESTful-0.4.3-py3-none-any.whl), rename it to the proper lower-case name, and then use `poetry add` to install it.
> 
> ```
> wget https://files.pythonhosted.org/packages/3d/f8/f152c23d669efab0c78ccbc9cb0500c3c1c2a07ab492cf9fac2ac91ffd74/FastApi_RESTful-0.4.3-py3-none-any.whl
> mv FastApi_RESTful-0.4.3-py3-none-any.whl fastapi_restful-0.4.3-py3-none-any.whl
> poetry add ./fastapi_restful-0.4.3-py3-none-any.whl
> ```
> 
> @yuval9313 if you could change the case of the project in `pyproject.toml` and rename the source directory, that would fix this issue.

@yuval9313 Could you please make the change for us to easy upgrade.

**Comment by yuval9313** [comment]
I wonder, is it possible to create both version with the original weird case and lower case one as well? I has some issues with pypi last time I tried to post the .whl file and hadn't gotten to it since

**Comment by yuval9313** [comment]
![image](https://github.com/yuval9313/FastApi-RESTful/assets/30751157/7b958c53-ca71-4d3c-a528-e9cf0d93dffe)

And in the second I will pass tests on master I will release a version for only-lowercase packages so pypi itself stop having issues with this package (leaving unresolved until then)

**Comment by yuval9313** [comment]
Works as of 0.4.5
